"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os 
from dotenv import load_dotenv
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Load the variables from .env
load_dotenv()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework',
    'corsheaders',
    # 'authentication',
    'authentication.apps.AuthenticationConfig',
    'django_rest_passwordreset',
   'rest_framework_simplejwt',
   'django_extensions',
   'analysis',
]

#password reset token
DJANGO_REST_PASSWORDRESET_TOKEN_CONFIG ={
    "CLASS" : "django_rest_passwordreset.tokens.RandomStringTokenGenerator",
    "OPTIONS":{
        "min_length": 20,
        "max_length": 40,
    }
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], #introducing the folder templates to django
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'), #database name
        'USER': os.getenv('DB_USER'), #the owner of the database i created
        'PASSWORD': os.getenv('DB_PASSWORD'), #password for the user
        'HOST' : 'localhost', #running locally
        'PORT': '5432',

    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    #tells Django exactly how to "read" the JSON you are sending from Next.js.
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',

    ),
}
#google sign in 
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')

FRONTEND_URL ="http://localhost:3000"

#Authorize django to speak with next.js
CORS_ALLOWED_ORIGINS=[
    "http://localhost:3000",
]

# without this, cookies are blocked by the browser
CORS_ALLOW_CREDENTIALS = True

#simple_jwt config

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,    #every refresh geta a new refresh token
    'BLACKLIST_AFTER_ROTATION': True, #old refresh token can't be reused
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}



#token expiration time : 30 minutes
DJANGO_REST_PASSWORDRESET_TOKEN_EXPIRY_TIME = 0.5
#Reset Password



#Reset Password email (brevo) 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST =  'smtp-relay.brevo.com' #smtp server
EMAIL_PORT = '587' 
EMAIL_USE_TLS = True

# #pulling values from .env file
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER') #brevo email
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD') #brevo smtp key value
#the email address users will see in the form field
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# #test (console)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'authentication':{
            'handlers':['console'],
            'level':'INFO',
        },
    },
}

#upstach 
CELERY_BROKER_URL= os.getenv("CELERY_BROKER_URL")
# Security and performance best practices
CELERY_BROKER_USE_SSL = {
    'ssl_cert_reqs': None
}
CELERY_REDIS_BACKEND_USE_SSL = {
    'ssl_cert_reqs': None
}