"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os 
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%%xjmb+d^e1&s!)!(m6wb-65^!1=y_!=buhjkf*4#1!s8)5e!q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    # 'authentication',
    'authentication.apps.AuthenticationConfig',
    'django_rest_passwordreset',
    'rest_framework.authtoken',
]

DJANGO_REST_PASSWORDRESET_TOKEN_CONFIG ={
    "CLASS" : "django_rest_passwordreset.tokens.RandomStringTokenGenerator",
    "OPTIONS":{
        "min_length": 20,
        "max_length": 40,
    }
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], #introducing the folder templates to django
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'seo_dashboard_db', #database name
        'USER': 'seo_user', #the owner of the database i created
        'PASSWORD': 'seouser123', #password for the user
        'HOST' : 'localhost', #running locally
        'PORT': '5432',

    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    #tells Django exactly how to "read" the JSON you are sending from Next.js.
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',

    ),
}


FRONTEND_URL ="http://localhost:3000"

CORS_ALLOWED_ORIGINS=[
    "http://localhost:3000",
]

#Authorize django to speak with next.js
CORS_ALLOW_ALL_ORIGINS = True


#token expiration time : 30 minutes
DJANGO_REST_MULTITOKENAUTH_RESET_TOKEN_EXPIRY_TIME = 0.5
#Reset Password

# Load the variables from .env
load_dotenv()

#Reset Password email (brevo) 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST =  'smtp-relay.brevo.com' #smtp server
EMAIL_PORT = '587' 
EMAIL_USE_TLS = True

# #pulling values from .env file
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER') #brevo email
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD') #brevo smtp key value
#the email address users will see in the form field
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# #test (console)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'