# Generated by Django 6.0.2 on 2026-04-13 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('github_repo_linked', models.CharField(blank=True, max_length=255, null=True)),
                ('ga4_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('ga4_refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('ga4_property_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
