# Generated by Django 6.0.2 on 2026-04-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_analysishistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisHistory',
        ),
    ]
