# Generated by Django 5.1.13 on 2026-05-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_analysishistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='ga4_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
