# Generated by Django 6.0.2 on 2026-06-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
