# Generated by Django 6.0.2 on 2026-06-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_delete_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='primary_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
